Vfd 194 lisataan testbed api iin endpointit joiden kautta voidaan kayttaa users api n productizeria basic information ja job applicant profile
Virtual-Finland-Development/testbed-api pull request #22
Opened 2023-02-08 10:39 UTC by lassipatanen

Lisätty endpointit BasicInformation ja JobApplicantProfile data tuotteiden lukua ja kirjoittamista varten.

2023-02-08 13:45 UTC, lsipii requested changes
Tämä näyttäisi olevan selkeä ja tyylin mukainen paketti! Korjaisisin vain tuon yhden data-product nimen perustietojen kirjoittamisessa.

Ajatuksena myöhempää tämän pr:n ulkopuolista kehittelyä varten: person-moduulin helpperit, kuten `build_data_product_uri`,  voisi kuulua productizers-moduuliin josta/jonka avuilla muutkin liittyvät tietoväylät voisivat muodostaa kyselynsä. Vaatisi vähän muiden tietolähteiden sorvaamista.

2023-02-08 13:45 UTC, lsipii commented on src/lib/api_app/src/api/routes/testbed/productizers/person/basic_information/mod.rs
> +    let data_product = "draft/Person/BasicInformation";
draft/Person/BasicInformation/Write

2023-02-08 15:09 UTC, lsipii commented on src/lib/api_app/src/api/routes/mod.rs
> +    return match get_router_response(parsed_request).await {
Tästä voisi jättää returnin ja puolipisteen pois

2023-02-09 06:21 UTC, lassipatanen commented on src/lib/api_app/src/api/routes/testbed/productizers/person/mod.rs
> +    let path: String = testbed_base_url + data_product + "?source=" + data_source + ":" + testbed_environment.as_str();
✅

2023-02-09 06:23 UTC, lassipatanen commented on src/lib/api_app/src/api/routes/mod.rs
> +    return match get_router_response(parsed_request).await {
✅

2023-02-09 06:24 UTC, lassipatanen commented on src/lib/api_app/src/api/routes/testbed/productizers/person/basic_information/mod.rs
> +    let data_product = "draft/Person/BasicInformation";
✅

2023-02-09 08:07 UTC, lsipii commented on src/lib/api_app/src/api/routes/testbed/productizers/person/mod.rs
> +    let path: String = testbed_base_url + data_product + "?source=" + data_source + ":" + testbed_environment.as_str();
Sorry tähän tuli huono esimerkki: kun `testbed_base_url` on ympäristömuuttujana: `https://gateway.testbed.fi/` niin ym. esimerkillä saa aikaiseksi osoitteen: `https://gateway.testbed.fi//draft/Person/BasicInformation?source=virtualfinland:vfd` <-- huom `//` <-- testbed gw ei osaa reitittää tuota

2023-02-09 08:12 UTC, lsipii commented on src/lib/api_app/src/api/routes/testbed/productizers/person/mod.rs
> +    let path: String = testbed_base_url + data_product + "?source=" + data_source + ":" + testbed_environment.as_str();
Eikun osaa se, vaihtui samaan aikaan tuo datalähteen tagi

2023-02-09 08:12 UTC, lsipii approved these changes

2023-02-09 10:37 UTC, merged